"""empty message

Revision ID: d0cc28661fe1
Revises: 91ac0e3fe7b2
Create Date: 2019-05-04 20:22:58.453607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cc28661fe1'
down_revision = '91ac0e3fe7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
